version: '3'

dotenv:
  - .env

tasks:
  api:build:
    desc: Build the api
    cmds:
      - go build -o bin/tarkov-build-optimiser-api ./cmd/tarkov-build-optimiser-api

  api:debug:
    desc: start the api locally in debug mode
    cmds:
      - dlv debug --listen=:4000 -log=true --accept-multiclient --api-version=2 ./cmd/tarkov-build-optimiser-api

  api:debug:headless:
    desc: start the api locally in headless debug mode
    cmds:
      - dlv debug --listen=:4000 -log=true --headless=true --accept-multiclient --api-version=2 ./cmd/tarkov-build-optimiser-api

  api:start:
    desc: start the api locally
    deps: [api:build, compose:up]
    cmds:
      - ./bin/tarkov-build-optimiser-api

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t tarkov-build-optimiser .

  clean:
    desc: Clean the project
    cmds:
      - go clean
      - rm -rf bin

  compose:postgres:up:
    desc: Start the local database
    cmds:
      - docker compose --env-file .env up -d postgres

  compose:up:
    desc: Start the local environment
    cmds:
      - docker compose --env-file .env up -d

  compose:restart:
    desc: Restart the local environment
    deps: [compose:down, compose:up]

  compose:down:
    desc: Stop the local environment
    cmds:
      - docker compose --env-file .env down

  importer:start:use-cache:
    desc: Start the importer - retrieve cached data instead of fetching from the tarkovdev API
    deps: [importer:build]
    cmds:
      - ./bin/tarkov-dev-importer --use-cache

  importer:start:cache-only:
    desc: Start the importer - only cache the data as json
    deps: [importer:build]
    cmd: ./bin/tarkov-dev-importer --cache-only

  importer:build:
    desc: Build the importer
    cmd: go build -o bin/tarkov-dev-importer ./cmd/tarkov-dev-importer

  importer:start:
    desc: Start the importer
    deps: [importer:build]
    cmd: ./bin/tarkov-dev-importer

  evaluator:build:
    desc: Build the weapon evaluator
    cmd: go build -o bin/weapon-evaluator ./cmd/weapon-evaluator

  evaluator:start:
    desc: Evaluate best ergo & recoil builds for all weapons & mods in db
    deps: [evaluator:build]
    cmd: ./bin/weapon-evaluator

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  migrate:create:
    desc: Create a new migration
    cmds:
      - goose -dir=./migrations create {{.CLI_ARGS}} go

  migrate:build:
    desc: Build the migrations
    cmds:
      - go build -o bin/migrate ./cmd/migrations/*.go

  migrate:down:
    desc: Rollback migrations
    deps: [compose:postgres:up, migrate:build]
    cmds:
      - ./bin/migrate postgres "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_PORT sslmode=disable" down

  migrate:up:
    desc: Apply migrations
    deps: [compose:postgres:up, migrate:build]
    cmd: ./bin/migrate postgres "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_PORT sslmode=disable" up

  start:local:
    desc: Start full local environment
    deps: [compose:start, api:start]

  test:
    desc: Run tests
    cmds:
      - go test ./...

  tarkovdev:get-schema:
    desc: Retrieve the latest schema from the tarkov.dev API
    cmd: graphql-inspector introspect https://api.tarkov.dev/api/graphql --write ./internal/tarkovdev/schemas/schema.graphql

  tarkovdev:regenerate:
    desc: Regenerate the tarkovdev client
    cmds:
      - go run github.com/Khan/genqlient

  tarkovdev:
    desc: Sync the tarkovdev schema and regenerate the client
    deps: [tarkovdev:get-schema, tarkovdev:regenerate]

  deps:install:go:
    desc: Install go dependencies
    cmds:
      - ./scripts/install-go-deps.sh

  deps:install:node:
    desc: Install node dependencies
    cmds:
      - ./scripts/install-node-deps.sh

  init:go-only:
    desc: Initialise the project for development (without nodejs/tarkovdev schema dependencies)
    deps: [deps:install:go, compose:up, migrate:up]

  init:
    desc: Initialise the project for development
    deps: [deps:install:go, deps:install:node, compose:up, migrate:up]

  env:
    desc: Print the environment variables
    cmds:
      - echo $PATH
