# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build migrations
      run: go build -v -o ./bin/migrations ./cmd/migrations
      
    - name: Build tarkov-dev-importer
      run: go build -v -o ./bin/tarkov-dev-importer ./cmd/tarkov-dev-importer

    - name: Build weapon-evaluator
      run: go build -v -o ./bin/weapon-evaluator ./cmd/weapon-evaluator

    - name: Test
      run: go test -v ./...
