# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: ./scripts/install-go-deps.sh

    - name: Build Migrations
      run: task migrate:build

    - name: Build Importer
      run: task importer:build

    - name: Build Evaluator
      run: task evaluator:build

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
          POSTGRES_DB: ci_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          nc -z localhost 5432 && echo "PostgreSQL is up!" && break
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: ./scripts/install-go-deps.sh

    - name: Build Migrations
      run: task migrate:build

    - name: Run Migrations
      run: task migrate:ci

    - name: Run Tests
      env:
        POSTGRES_HOST: postgres
        POSTGRES_USER: ci_user
        POSTGRES_PASSWORD: ci_password
        POSTGRES_DB: ci_db
        POSTGRES_PORT: 5432
      run: task test
